[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cdbassett_advent_of_code_python"
version = "0.1.5"
dependencies = [
    "advent-of-code-data>=2.2.0",
    "colorama>=0.4.6",
    "construct>=2.10.70",
    "pyfunctional>=1.5.0",
    "icecream>=2.2.0",
    "iteration-utilities>=0.13.0",
    "matplotlib>=3.11.1",
    "networkx>=3.6.1",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "pyparsing>=3.3.2",
    "pyperclip>=1.11.0",
    "requests>=2.34.2",
    "scipy>=1.18.0",
    "shapely>=2.1.2",
    "sympy>=1.14.0",
    "tabulate>=0.10.0",
    "z3-solver>=5.0.0.0",
    "mini-lambda>=2.2.3",
    "browser-cookie3>=0.20.1",
    "portion>=2.6.2",
    "parse>=1.22.1",
    "python-ranges>=1.2.2",
]

[tool.setuptools.packages.find]
where = ["."]